import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./themeprovider";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <head>
                <link rel="icon" href="/images/favicon.ico" />
            </head>
            <body className={inter.className}>
                <ThemeProvider attribute="class" defaultTheme="system">
                    <Navbar />
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
}
